/* jslint browser: true */
export default [
    'compass-arrow',
    'sea-sand',
    'canvas',
    'map-canvas',
    'matrix-svg',
    'audio-control',
    'music-control',
    'audio-control-audio-off',
    'audio-control-audio-on',
    'audio-control-music-off',
    'audio-control-music-on',
    'help',
    'help-popup',
    'help-close',
    'restart-game-button',
    'start-popup',
    'start-game-button',
    'start-game-seed',
    'ui-controls',
    'game-over-popup',
    'try-again-button',
    'win-popup',
    'new-game-button',
];
